# Generated by Django 4.2.7 on 2023-12-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Originality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tid',
            field=models.IntegerField(unique=True),
        ),
    ]
