# Generated by Django 4.2.7 on 2023-12-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_originality_alter_post_tid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Originality',
        ),
    ]
