# Generated by Django 4.2.7 on 2023-12-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_originality_tags_version_post_ori_post_tags_post_ver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
