# Generated by Django 4.2.7 on 2023-12-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_rename_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ver',
        ),
        migrations.AddField(
            model_name='post',
            name='ver',
            field=models.ManyToManyField(null=True, related_name='mcver', to='resource.version'),
        ),
    ]
