# Generated by Django 4.2.7 on 2023-12-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_remove_post_ver_post_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ver',
            field=models.ManyToManyField(blank=True, related_name='mcver', to='resource.version'),
        ),
    ]
