# Generated by Django 4.2.7 on 2023-12-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_alter_post_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='resource.originality'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ver',
            field=models.ManyToManyField(related_name='mcver', to='resource.version'),
        ),
    ]
