# Generated by Django 4.2.7 on 2023-12-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0009_alter_post_ori_alter_post_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seriousness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriousness', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='VS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('uid', models.IntegerField()),
                ('occurance', models.TextField()),
                ('tid', models.IntegerField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_expire', models.DateField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('v_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasion_board', to='resource.board')),
                ('v_seriousness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasion_seriousness', to='broken.seriousness')),
                ('v_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasion_type', to='broken.type')),
            ],
        ),
    ]
